USE Testing
GO
IF EXISTS (SELECT * FROM dbo.SYSOBJECTS WHERE ID = OBJECT_ID(N'CustomerData') AND OBJECTPROPERTY(ID, N'IsUserTable') = 1)
DROP TABLE [dbo].[CustomerData]
CREATE TABLE [dbo].[CustomerData] (
	ID VARCHAR(50) NULL,
	FIRST_NAME VARCHAR(50) NULL,
	LAST_NAME VARCHAR(50) NULL,
	GENDER VARCHAR(50) NULL,
	COMPANY_NAME VARCHAR(50) NULL
) ON [PRIMARY]
GO
--CHANGE COMPANY NAME TO UPPER CASE
UPDATE [CustomerData]
SET COMPANY_NAME = UPPER(COMPANY_NAME)
GO
--CHANGE THE GENDER TO LOWER CASE
UPDATE [CustomerData]
SET GENDER = LOWER(GENDER)
GO
SELECT * FROM [CustomerData]
